# Generated by Django 5.1.6 on 2025-02-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_reciepe_reciepy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='reciepy_image',
            field=models.ImageField(upload_to='reciepy'),
        ),
    ]
