# Generated by Django 5.1.6 on 2025-02-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
